### ISSUE TITLE
e-Tex? 

### ISSUE THREAD

**Issue by elliott-wen** [nadder/rstex#4]
Just wondering whether the repo contains e-tex supports?

Cheers

**Comment by nadder** [comment]
No e-tex support yet.  Would be nice have an e-tex version as well.

**Comment by elliott-wen** [comment]
Ok, I will send a pull request after I add it. One thing I am still a bit confused about is  that does this application still require a string pool file?

**Comment by nadder** [comment]
Yes, like the original TeX all the strings are put in a tex.pool file. This is done by the CreatePoolFile program. So the procedure is to first compile CreatePoolFile, then you run the command `CreatePoolFile TEX_STRING rstex.cpp.pre rstex.h.pre`
This produces the three files rstex.cpp, rstex.h and tex.pool.

**Comment by nadder** [comment]
Not happening.

**Comment by nadder** [comment]
> Just wondering whether the repo contains e-tex supports?
> 
> Cheers

It does now!
